// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

import './globals.css';
import Navbar from '../app/components/Navbar';
import Footer from '../app/components/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import FABWhatsApp from './components/fabComponents/FABWhatsApp';
import FABLocation from './components/fabComponents/FABLocation';

export const metadata = {
  title: 'Deal Magsil',
  description: 'A professional Cement product Manufracture',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <FABLocation/>
        <FABWhatsApp/>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
